### ISSUE TITLE
Data transmission failure of non directly connected device

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-nRF-Mesh-Library#427]
---

**Describe the bug**
VendorModelMessageAcked Send data `F1C809CB3132333435363738393031323334353637383930313233343536373839 `. The direct connected device sends successfully and receives a reply. The non direct connected device does not respond

The data length is 33. If I only send data below 33, there is no problem

**Platform details:**
 - Device: HuaWei P40 Pro
 - OS: android 10
 - Library Version 3.1.1

**Logs / Screenshots**

The log of direct connected device is as follows：

```
2021-05-08 16:12:21.667 18506-18506/com.xuntong.meshuart V/MeshTransport: Src address: 1990
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: Dst address: 0017
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: Key: 4E3EDD70BFC8172A06B5A5E531439CD8
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: akf: 1
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: aid: 63
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: aszmic: 0
2021-05-08 16:12:21.668 18506-18506/com.xuntong.meshuart V/MeshTransport: Sequence number: 2964
2021-05-08 16:12:21.669 18506-18506/com.xuntong.meshuart V/MeshTransport: Access message opcode: f1
2021-05-08 16:12:21.669 18506-18506/com.xuntong.meshuart V/MeshTransport: Access message parameters: 123132333435363738393031323334353637383930313233343536373839
2021-05-08 16:12:21.670 18506-18506/com.xuntong.meshuart V/AccessLayer: Created Access PDU F1C809123132333435363738393031323334353637383930313233343536373839
2021-05-08 16:12:21.670 18506-18506/com.xuntong.meshuart V/UpperTransportLayer: Application nonce: 0100000B941990001700000000
2021-05-08 16:12:21.671 18506-18506/com.xuntong.meshuart V/UpperTransportLayer: Encrypted upper transport pdu: E3E5FA564A21C38693B50D12874920A37901027EED6F09A1027AFADC366AB1C99B2455AEFA
2021-05-08 16:12:21.672 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E5003E3E5FA564A21C38693B50D12 0 of 4
2021-05-08 16:12:21.674 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E5023874920A37901027EED6F09A1 1 of 4
2021-05-08 16:12:21.674 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E5043027AFADC366AB1C99B2455AE 2 of 4
2021-05-08 16:12:21.674 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E5063FA 3 of 4
2021-05-08 16:12:21.675 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encryption key: 06358353B92CC8027DD1BAFD2006D648
2021-05-08 16:12:21.675 18506-18506/com.xuntong.meshuart V/NetworkLayer: Privacy key: 68751462A589E2F9DE9400E7A2D466C4
2021-05-08 16:12:21.676 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B94
2021-05-08 16:12:21.677 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 61E6EF16B6713C3F6A3C3A288C01CE5031CA5C1C06E0
2021-05-08 16:12:21.678 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B95
2021-05-08 16:12:21.679 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 7DF3A46E6000058130AD31777DF7AE4F91169B76C63E
2021-05-08 16:12:21.680 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B96
2021-05-08 16:12:21.681 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: A1C04ACFD344145165BAA79D6B24DD117DE9093480EB
2021-05-08 16:12:21.682 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B97
2021-05-08 16:12:21.683 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 5E64CEB1217A55C8558AFF
2021-05-08 16:12:21.684 18506-18506/com.xuntong.meshuart V/VendorModelMessageAckedState: Sending acknowledged vendor model message
2021-05-08 16:12:21.686 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:21.686 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:21.707 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-1A-56-93-F7-5F-BA-61-E6-EF-16-B6-71-3C-3F-6A-3C-3A-28-8C-01-CE-50-31-CA-5C-1C-06-E0
2021-05-08 16:12:21.707 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x00611A5693F75FBA61E6EF16B6713C3F6A3C3A288C01CE5031CA5C1C06E0
2021-05-08 16:12:21.707 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:21.707 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:21.722 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-31-87-D4-B0-AB-11-7D-F3-A4-6E-60-00-05-81-30-AD-31-77-7D-F7-AE-4F-91-16-9B-76-C6-3E
2021-05-08 16:12:21.722 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x00613187D4B0AB117DF3A46E6000058130AD31777DF7AE4F91169B76C63E
2021-05-08 16:12:21.722 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:21.722 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:21.725 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-66-6E-80-63-48-8A-A1-C0-4A-CF-D3-44-14-51-65-BA-A7-9D-6B-24-DD-11-7D-E9-09-34-80-EB
2021-05-08 16:12:21.725 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x0061666E8063488AA1C04ACFD344145165BAA79D6B24DD117DE9093480EB
2021-05-08 16:12:21.725 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:21.725 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:21.728 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-5E-EE-26-CD-FC-6C-5E-64-CE-B1-21-7A-55-C8-55-8A-FF
2021-05-08 16:12:21.728 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x00615EEE26CDFC6C5E64CEB1217A55C8558AFF
2021-05-08 16:12:21.992 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-C7-5A-59-94-0D-D3-3C-2D-30-47-11-5A-CE-8E-D1-C5-37-BA-7C-E3-A5-16-07
2021-05-08 16:12:21.993 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x0061C75A59940DD33C2D3047115ACE8ED1C537BA7CE3A51607
2021-05-08 16:12:21.993 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 8
2021-05-08 16:12:21.993 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 8193
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 8
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Acknowledgement payload: 0000000F
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 0 of 3 received by peer
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 1 of 3 received by peer
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 2 of 3 received by peer
2021-05-08 16:12:21.994 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 3 of 3 received by peer
2021-05-08 16:12:21.995 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-53-45-85-49-49-B6-96-9E-66-9E-18-2A-2E-AF-70-5E-3A-6D-A0-03-12-8E-35-2A-32-75-2A-74
2021-05-08 16:12:21.995 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x00615345854949B6969E669E182A2EAF705E3A6DA003128E352A32752A74
2021-05-08 16:12:21.995 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 5
2021-05-08 16:12:21.995 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 8194
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 5
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/NetworkLayer: Dst: 0x1990
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/NetworkLayer: Received a segmented access message from: 0017
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG O: 0
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG N: 3
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Last SeqAuth value 18
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Current SeqAuth value 8194
2021-05-08 16:12:21.996 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Starting incomplete timer for src: 0017
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack value: 1
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: TTL: 5
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Duration: 400
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Message reassembly may not be completed yet!
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-A9-58-33-95-C2-20-13-64-C0-2C-2F-78-D2-E1-D1-E4-83-B5-99-38-06-91-B9-D0-99-F4-6A-2B
2021-05-08 16:12:21.997 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x0061A9583395C2201364C02C2F78D2E1D1E483B599380691B9D099F46A2B
2021-05-08 16:12:21.998 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 5
2021-05-08 16:12:21.998 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 8195
2021-05-08 16:12:21.998 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 5
2021-05-08 16:12:21.998 18506-18506/com.xuntong.meshuart V/NetworkLayer: Dst: 0x1990
2021-05-08 16:12:21.998 18506-18506/com.xuntong.meshuart V/NetworkLayer: Received a segmented access message from: 0017
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG O: 1
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG N: 3
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Last SeqAuth value 8194
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Current SeqAuth value 8194
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Received segment message count: 2
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack value: 3
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Restarting incomplete timer for src: 0017
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Message reassembly may not be completed yet!
2021-05-08 16:12:21.999 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-01-23-A7-10-11-95-22-8C-73-EA-14-CF-F3-41-03-06-FC-25-77-25-57-44-C2-87-A8-B1-10-F5
2021-05-08 16:12:22.000 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x00610123A7101195228C73EA14CFF3410306FC2577255744C287A8B110F5
2021-05-08 16:12:22.000 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 5
2021-05-08 16:12:22.000 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 8196
2021-05-08 16:12:22.000 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 5
2021-05-08 16:12:22.000 18506-18506/com.xuntong.meshuart V/NetworkLayer: Dst: 0x1990
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/NetworkLayer: Received a segmented access message from: 0017
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG O: 2
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG N: 3
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Last SeqAuth value 8194
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Current SeqAuth value 8194
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Received segment message count: 3
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack value: 7
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Restarting incomplete timer for src: 0017
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Message reassembly may not be completed yet!
2021-05-08 16:12:22.001 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-E9-B9-D0-7B-61-2D-65-58-51-E3-D6-9B-C6-81-23-81-9E
2021-05-08 16:12:22.002 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x0061E9B9D07B612D655851E3D69BC68123819E
2021-05-08 16:12:22.002 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 5
2021-05-08 16:12:22.002 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 8197
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 5
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/NetworkLayer: Dst: 0x1990
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/NetworkLayer: Received a segmented access message from: 0017
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG O: 3
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: SEG N: 3
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Last SeqAuth value 8194
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Current SeqAuth value 8194
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Received segment message count: 4
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack value: f
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack: 15
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: bit count: 3
2021-05-08 16:12:22.003 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Block acknowledgement payload: 00080000000F
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart E/LowerTransportLayer: sendBlockAck:src: 6544 dst:23
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Creating unsegmented transport control
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Unsegmented Lower transport control PDU 0000080000000F
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encryption key: 06358353B92CC8027DD1BAFD2006D648
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/NetworkLayer: Privacy key: 68751462A589E2F9DE9400E7A2D466C4
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B98
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 774BA8FA0D34B60C1F8576CC36EB2E1538
2021-05-08 16:12:22.004 18506-18506/com.xuntong.meshuart V/MeshMessageState: Sending acknowledgement: 00614BD69930212A774BA8FA0D34B60C1F8576CC36EB2E1538
2021-05-08 16:12:22.005 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:22.005 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:22.007 18506-18506/com.xuntong.meshuart V/AccessLayer: Received Access PDU F3C809123132333435363738393031323334353637383930313233343536373839 opCode:f3c809
2021-05-08 16:12:22.007 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: XT_UART model Access PDU Received: F3C809123132333435363738393031323334353637383930313233343536373839
2021-05-08 16:12:22.007 18506-18506/com.xuntong.meshuart V/VendorModelMessageStatus: Received Vendor model status: 123132333435363738393031323334353637383930313233343536373839
2021-05-08 16:12:22.007 18506-18506/com.xuntong.meshuart E/MeshService: VendorModelMessageStatus 0x123132333435363738393031323334353637383930313233343536373839 opcode:f3c809
2021-05-08 16:12:22.010 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-4B-D6-99-30-21-2A-77-4B-A8-FA-0D-34-B6-0C-1F-85-76-CC-36-EB-2E-15-38
2021-05-08 16:12:22.010 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x00614BD69930212A774BA8FA0D34B60C1F8576CC36EB2E1538
2021-05-08 16:12:22.398 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Acknowledgement timer expiring
2021-05-08 16:12:22.398 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Block ack: 15
2021-05-08 16:12:22.399 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: bit count: 3
2021-05-08 16:12:22.399 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Block acknowledgement payload: 00080000000F
2021-05-08 16:12:22.400 18506-18506/com.xuntong.meshuart E/LowerTransportLayer: sendBlockAck:src: 6544 dst:23
2021-05-08 16:12:22.400 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Creating unsegmented transport control
2021-05-08 16:12:22.401 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Unsegmented Lower transport control PDU 0000080000000F
2021-05-08 16:12:22.401 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encryption key: 06358353B92CC8027DD1BAFD2006D648
2021-05-08 16:12:22.401 18506-18506/com.xuntong.meshuart V/NetworkLayer: Privacy key: 68751462A589E2F9DE9400E7A2D466C4
2021-05-08 16:12:22.402 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B99
2021-05-08 16:12:22.403 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: E9EFA158D7FC5D2988338DB210DCE0E08F
2021-05-08 16:12:22.404 18506-18506/com.xuntong.meshuart V/MeshMessageState: Sending acknowledgement: 006141F91FBC1021E9EFA158D7FC5D2988338DB210DCE0E08F
2021-05-08 16:12:22.407 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:12:22.408 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:12:22.416 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-41-F9-1F-BC-10-21-E9-EF-A1-58-D7-FC-5D-29-88-33-8D-B2-10-DC-E0-E0-8F
2021-05-08 16:12:22.416 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x006141F91FBC1021E9EFA158D7FC5D2988338DB210DCE0E08F

```
The log of non directly connected devices is as follows:

```
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Src address: 1990
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Dst address: 0016
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Key: 4E3EDD70BFC8172A06B5A5E531439CD8
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: akf: 1
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: aid: 63
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: aszmic: 0
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Sequence number: 2959
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Access message opcode: f1
2021-05-08 16:10:17.916 18506-18506/com.xuntong.meshuart V/MeshTransport: Access message parameters: CB3132333435363738393031323334353637383930313233343536373839
2021-05-08 16:10:17.917 18506-18506/com.xuntong.meshuart V/AccessLayer: Created Access PDU F1C809CB3132333435363738393031323334353637383930313233343536373839
2021-05-08 16:10:17.917 18506-18506/com.xuntong.meshuart V/UpperTransportLayer: Application nonce: 0100000B8F1990001600000000
2021-05-08 16:10:17.917 18506-18506/com.xuntong.meshuart V/UpperTransportLayer: Encrypted upper transport pdu: F5EB06D2AEAF43CBAC4D85892834DD1289608A6B0BBB633E388045F58F12AD97FD4668F397
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E3C03F5EB06D2AEAF43CBAC4D8589 0 of 4
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E3C232834DD1289608A6B0BBB633E 1 of 4
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E3C43388045F58F12AD97FD4668F3 2 of 4
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/LowerTransportLayer: Segmented Lower transport access PDU: FF2E3C6397 3 of 4
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encryption key: 06358353B92CC8027DD1BAFD2006D648
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/NetworkLayer: Privacy key: 68751462A589E2F9DE9400E7A2D466C4
2021-05-08 16:10:17.918 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B8F
2021-05-08 16:10:17.919 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: E96245B578E9AD1A14EF78CC75605C9CCE36155C4C28
2021-05-08 16:10:17.919 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B90
2021-05-08 16:10:17.920 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 8586ED6BEC9643613EE0AE6E41EC617F6229DB49203A
2021-05-08 16:10:17.920 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B91
2021-05-08 16:10:17.920 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 50CD39721B3366AC7BBF4CB19219D19954D77F1FB12E
2021-05-08 16:10:17.920 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B92
2021-05-08 16:10:17.921 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 63EC86C13DCFBB0D07FBBB
2021-05-08 16:10:17.922 18506-18506/com.xuntong.meshuart V/VendorModelMessageAckedState: Sending acknowledged vendor model message
2021-05-08 16:10:17.924 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:10:17.924 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:10:17.951 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-D3-D9-6C-22-84-D4-E9-62-45-B5-78-E9-AD-1A-14-EF-78-CC-75-60-5C-9C-CE-36-15-5C-4C-28
2021-05-08 16:10:17.951 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x0061D3D96C2284D4E96245B578E9AD1A14EF78CC75605C9CCE36155C4C28
2021-05-08 16:10:17.952 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:10:17.952 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:10:17.957 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-CE-90-13-D7-35-F5-85-86-ED-6B-EC-96-43-61-3E-E0-AE-6E-41-EC-61-7F-62-29-DB-49-20-3A
2021-05-08 16:10:17.957 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x0061CE9013D735F58586ED6BEC9643613EE0AE6E41EC617F6229DB49203A
2021-05-08 16:10:17.958 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:10:17.958 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:10:17.959 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-A3-35-9E-C1-CF-D8-50-CD-39-72-1B-33-66-AC-7B-BF-4C-B1-92-19-D1-99-54-D7-7F-1F-B1-2E
2021-05-08 16:10:17.959 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x0061A3359EC1CFD850CD39721B3366AC7BBF4CB19219D19954D77F1FB12E
2021-05-08 16:10:17.959 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:10:17.959 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:10:17.961 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-73-E3-03-6D-38-51-63-EC-86-C1-3D-CF-BB-0D-07-FB-BB
2021-05-08 16:10:17.961 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x006173E3036D385163EC86C13DCFBB0D07FBBB
2021-05-08 16:10:19.167 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-7F-11-14-A6-BC-AA-5F-36-1F-1D-C6-CA-3C-6F-9C-D3-39-85-97-F2-3D-ED-36
2021-05-08 16:10:19.167 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x00617F1114A6BCAA5F361F1DC6CA3C6F9CD3398597F23DED36
2021-05-08 16:10:19.168 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 7
2021-05-08 16:10:19.169 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 24795
2021-05-08 16:10:19.170 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 7
2021-05-08 16:10:19.172 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Acknowledgement payload: 00000003
2021-05-08 16:10:19.173 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 0 of 3 received by peer
2021-05-08 16:10:19.173 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 1 of 3 received by peer
2021-05-08 16:10:19.173 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 2 of 3 not received by peer
2021-05-08 16:10:19.173 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 3 of 3 not received by peer
2021-05-08 16:10:19.174 18506-18506/com.xuntong.meshuart V/MeshMessageState: Resending segment 2 : 0061A3359EC1CFD850CD39721B3366AC7BBF4CB19219D19954D77F1FB12E
2021-05-08 16:10:19.174 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encryption key: 06358353B92CC8027DD1BAFD2006D648
2021-05-08 16:10:19.175 18506-18506/com.xuntong.meshuart V/NetworkLayer: Privacy key: 68751462A589E2F9DE9400E7A2D466C4
2021-05-08 16:10:19.175 18506-18506/com.xuntong.meshuart V/NetworkLayer: Sequence Number: 000B93
2021-05-08 16:10:19.177 18506-18506/com.xuntong.meshuart V/NetworkLayer: Encrypted Network payload: 90484D08F875B9C68871C3E30051231634005DB9A310
2021-05-08 16:10:19.181 18506-18506/com.xuntong.meshuart V/BleManager: Writing characteristic 00002add-0000-1000-8000-00805f9b34fb (WRITE COMMAND)
2021-05-08 16:10:19.181 18506-18506/com.xuntong.meshuart D/BleManager: gatt.writeCharacteristic(00002add-0000-1000-8000-00805f9b34fb)
2021-05-08 16:10:19.187 18506-18506/com.xuntong.meshuart I/BleManager: Data written to 00002add-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-C6-0C-8C-91-03-73-90-48-4D-08-F8-75-B9-C6-88-71-C3-E3-00-51-23-16-34-00-5D-B9-A3-10
2021-05-08 16:10:19.187 18506-18506/com.xuntong.meshuart V/MeshManagerApi: MeshNetwork pdu sent: 0x0061C60C8C91037390484D08F875B9C68871C3E30051231634005DB9A310
2021-05-08 16:10:20.270 18506-18506/com.xuntong.meshuart I/BleManager: Notification received from 00002ade-0000-1000-8000-00805f9b34fb, value: (0x) 00-61-44-52-C2-34-3C-16-B6-43-5E-50-7D-63-70-FD-86-FE-37-94-5D-59-5F-00-58
2021-05-08 16:10:20.271 18506-18506/com.xuntong.meshuart V/MeshManagerApi: Received network pdu: 0x00614452C2343C16B6435E507D6370FD86FE37945D595F0058
2021-05-08 16:10:20.272 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: TTL for received message: 7
2021-05-08 16:10:20.273 18506-18506/com.xuntong.meshuart V/BaseMeshMessageHandler: Sequence number of received access message: 24796
2021-05-08 16:10:20.274 18506-18506/com.xuntong.meshuart V/NetworkLayer: TTL for received message: 7
2021-05-08 16:10:20.276 18506-18506/com.xuntong.meshuart V/DefaultNoOperationMessageState: Acknowledgement payload: 00000007
2021-05-08 16:10:20.276 18506-18506/com.xuntong.meshuart V/BlockAcknowledgementMessage: Segment 0 of 0 received by peer

```

**Comment by Nuclear6** [comment]
Is the direct connected device set proxy white list, include provisioner address?
The non direct connected device will adv response, these data  will arrive first the direct connected device, and then check dst address in white list. if in white list, the direct connected device will send data to Provisioner.
Hope it helps you!!!

**Comment by kcjian** [comment]
@Nuclear6 No, I am not allowed to add provisioner address to the proxy white list in the app

**Comment by roshanrajaratnam** [comment]
Duplicate of #426

**Comment by roshanrajaratnam** [comment]
@kcjian  could you test this issue against the latest dev branch please? I have fixed an underlying GATT level segmentation issue where sometimes the lib was waiting for messages when it should not.

**Comment by roshanrajaratnam** [comment]
Closing due to inactivity and we can continue the discussion on #426

**Comment by kcjian** [comment]
@roshanrajaratnam 
I tested nrfmesh version 3.1.5, but the problem still exists

When successful：send 32 bytes
Send：       F1C8091234567890123456789012345678901234567890123456789012345678
Received：F3C8091234567890123456789012345678901234567890123456789012345678
![Screenshot_20210610-142925](https://user-images.githubusercontent.com/15611112/121476372-29304100-c9f9-11eb-9218-40bfcaae2eca.png)


On failure：Add one byte, the data reaches 33 bytes
Send:          F1C809123456789012345678901234567890123456789012345678901234567890
Received：time out
![Screenshot_20210610-142952](https://user-images.githubusercontent.com/15611112/121476387-2c2b3180-c9f9-11eb-8c73-43bc265d5ce8.png)

[log_successful.txt](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/files/6628954/log_successful.txt)
[log_failed.txt](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/files/6628955/log_failed.txt)


**There's no problem with direct connected device**
Send：       F1C809123456789012345678901234567890123456789012345678901234567890
Received：F3C809123456789012345678901234567890123456789012345678901234567890

[log_successful_direct_device_with_33_bytes.txt](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/files/6628963/log_successful_direct_device_with_33_bytes.txt)

**Comment by roshanrajaratnam** [comment]
did you test the version from dev branch?

**Comment by kcjian** [comment]
@roshanrajaratnam Yes, the result is the same

**Comment by roshanrajaratnam** [comment]
Could you share your fw ? if it's based on nRF 5Sdk could you share the fw bundled with the softdevice please?

**Comment by kcjian** [comment]
Yes, I'm planning to make the simplest demo, including a vendor model, which can reply to whatever I send. It may be provided to you tomorrow or next week

**Comment by roshanrajaratnam** [comment]
great that would be very helpful to debug this.

**Comment by kcjian** [comment]
![Screenshot_20210611-100931](https://user-images.githubusercontent.com/15611112/121620638-428ac900-ca9d-11eb-95a5-65c48082f879.png)

- Vendor Modek : 0x00590000
- OpCode: 0xC1
- Parameters: 0x123456789012345678901234567890123456789012345678901234567890

A minimum of two devices are required


[light_switch_server_nrf52832_xxAA_s132_7.2.0.hex.zip](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/files/6635339/light_switch_server_nrf52832_xxAA_s132_7.2.0.hex.zip)

**Comment by roshanrajaratnam** [comment]
Great will take a look at this now, is this bundled with the soft device?

**Comment by roshanrajaratnam** [comment]
Hi @kcjian so I managed to reproduce your issue and after some hours of debugging found the root cause.

**Comment by kcjian** [comment]
Can you send and receive successfully on non direct connected devices？

**Comment by roshanrajaratnam** [comment]
yes it works for devices when they are not connected directly. This was more of an issue on the network layer causing this to happen.

**Comment by roshanrajaratnam** [comment]
@kcjian oops I missed one file in my commit :( . Check the latest commit :)

**Comment by kcjian** [comment]
That's right, I can receive the correct reply，Thanks for your work.

And Can you take a look at this problem that still exists

[#406](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/issues/406)

The same happens in non direct connected devices.

**Comment by roshanrajaratnam** [comment]
I believe this should also be fixed with the current fix.

**Comment by kcjian** [comment]
But I tested the above test method, which shows that this problem still exists,I'll test it again

![WeChat2c3cc93ee31587bea35409ba7d418154](https://user-images.githubusercontent.com/15611112/121674194-51489e80-cae4-11eb-8b70-f8ec7b5ac5d8.png)

**Comment by roshanrajaratnam** [comment]
ok let's move the conversion to the other issue. I will close this now.
